---
- name: Setup Xian ABCI application on Ubuntu 22.04
  hosts: validators:service_nodes
  become: yes
  vars:
    python_version: "3.11"
    xian_repo: "https://github.com/xian-network/xian-core.git"
    contracting_repo: "https://github.com/xian-network/contracting.git"
    cometbft_version: "0.38.6"
    cometbft_url: "https://github.com/cometbft/cometbft/releases/download/v{{ cometbft_version }}/cometbft_{{ cometbft_version }}_linux_amd64.tar.gz"

    validator_privkey: "{{sk}}"
    moniker: "{{inventory_hostname}}"
    genesis_file_name: "genesis-testnet.json"
    # Add the seed node IP if joining an existing network
    seed_node_address: "{{None if inventory_hostname == 'testnet_1' else '392a05fe83a27cd75f7431f070cfb57446d1e93b@116.203.81.165'}}"

  tasks:

    - name: Clone Xian Stack Development Environment repository
      git:
        repo: 'https://github.com/xian-network/xian-stack-dev-env.git'
        dest: '/root/xian-stack'
        clone: yes
        update: yes

    - name: Clone Xian Core repository
      git:
        repo: 'https://github.com/xian-network/xian-core.git'
        dest: '/root/xian-stack/xian-core'
        version: "{{ CORE_BRANCH }}"
        clone: yes
        update: yes

    - name: Clone Xian Contracting repository
      git:
        repo: 'https://github.com/xian-network/xian-contracting.git'
        dest: '/root/xian-stack/xian-contracting'
        version: "{{ CONTRACTING_BRANCH }}"
        clone: yes
        update: yes

    - name: Build core development environment
      ansible.builtin.shell:
        chdir: /root/xian_stack
        cmd: make core-dev-build

    - name: Start core development environment
      ansible.builtin.shell:
        chdir: /root/xian_stack
        cmd: make core-dev-up

    - name: Initialize the environment
      ansible.builtin.shell:
        chdir: /root/xian_stack
        cmd: make init

    - name: Configure the environment
      ansible.builtin.shell:
        chdir: /root/xian_stack
        cmd: >
          make configure CONFIGURE_ARGS='--moniker "{{moniker}}" --genesis-file-name "{{genesis_file_name}}" --validator-privkey "{{validator_privkey}}" --seed-node-address "{{seed_node_address}}" --copy-genesis True'
