---
- name: Disable Nginx on target machines
  hosts: validators:service_nodes
  become: yes  # Use sudo to become root, necessary for stopping and disabling services

  tasks:
    - name: Stop Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: stopped

    - name: Disable Nginx service
      ansible.builtin.systemd:
        name: nginx
        enabled: no