---
- name: Setup project with venv and Makefile
  hosts: validators:service_nodes
  become: yes

  tasks:

    - name: Nodes down
      ansible.builtin.shell: |
        make down
      args:
        chdir: "/root/xian-stack"
        executable: /bin/bash
      ignore_errors: yes
      become: yes

    - name: Wipe nodes
      ansible.builtin.shell: |
        make wipe
      args:
        chdir: "/root/xian-stack"
        executable: /bin/bash
      ignore_errors: yes
      become: yes

    - name: Docker down
      ansible.builtin.shell: |
        make core-dev-down
      args:
        chdir: "/root/xian-stack"
        executable: /bin/bash
      ignore_errors: yes
      become: yes

    - name: Wipe BDS
      ansible.builtin.shell: |
        make wipe-bds
      args:
        chdir: "/root/xian-stack"
        executable: /bin/bash
      ignore_errors: yes
      become: yes

    - name: Docker Up
      ansible.builtin.shell: |
        make core-dev-up
      args:
        chdir: "/root/xian-stack"
        executable: /bin/bash
      become: yes

    - name: Nodes up
      ansible.builtin.shell: |
        make up
      args:
        chdir: "/root/xian-stack"
        executable: /bin/bash
      become: yes
