---
- name: Install and setup environment dependencies for Xian on Ubuntu 22.04
  hosts: validators:service_nodes
  become: yes
  vars:
    python_version: "3.11"

  tasks:
    - name: Update and add required PPA
      apt:
        name: software-properties-common
        state: present
      notify: Add deadsnakes PPA

    - name: Install necessary packages
      apt:
        name:
          - "pkg-config"
          - "python{{ python_version }}"
          - "python{{ python_version }}-dev"
          - "python{{ python_version }}-venv"
          - "libhdf5-dev"
          - "build-essential"
        update_cache: yes

    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.0/node_exporter-1.8.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-1.8.0.linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Node Exporter
      unarchive:
        src: "/tmp/node_exporter-1.8.0.linux-amd64.tar.gz"
        dest: "/opt"
        remote_src: yes
        creates: "/opt/node_exporter-1.8.0.linux-amd64"

    - name: Create Node Exporter systemd service file
      copy:
        dest: "/etc/systemd/system/node_exporter.service"
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          ExecStart=/opt/node_exporter-1.8.0.linux-amd64/node_exporter

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install PM2 globally using npm
      ansible.builtin.command:
        cmd: npm install pm2@latest -g

    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Allow CometBFT REST API port
      ufw:
        rule: allow
        port: 26657
        proto: tcp

    - name: Allow CometBFT Node Communication port
      ufw:
        rule: allow
        port: 26656
        proto: tcp

    - name: Allow CometBFT Prometheus Metrics port
      ufw:
        rule: allow
        port: 26660
        proto: tcp

    - name: Allow Prometheus Node Exporter Port
      ufw:
        rule: allow
        port: 9100
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        policy: allow
        direction: incoming

  handlers:
    - name: Add deadsnakes PPA
      apt_repository:
        repo: "ppa:deadsnakes/ppa"
        state: present
        update_cache: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes
