---
- name: Install and setup environment dependencies for Xian on Ubuntu 22.04
  hosts: validators:service_nodes
  become: yes
  vars:
    python_version: "3.11"
    xian_repo: "https://github.com/xian-network/xian-core.git"
    contracting_repo: "https://github.com/xian-network/contracting.git"
    cometbft_version: "0.38.6"
    cometbft_url: "https://github.com/cometbft/cometbft/releases/download/v{{ cometbft_version }}/cometbft_{{ cometbft_version }}_linux_amd64.tar.gz"

  tasks:
    - name: Update and add required PPA
      apt:
        name: software-properties-common
        state: present
      notify: Add deadsnakes PPA

    - name: Install necessary packages
      apt:
        name:
          - "pkg-config"
          - "python{{ python_version }}"
          - "python{{ python_version }}-dev"
          - "python{{ python_version }}-venv"
          - "libhdf5-dev"
          - "build-essential"
        update_cache: yes

    - name: Download and setup CometBFT
      block:
        - name: Download CometBFT
          get_url:
            url: "{{ cometbft_url }}"
            dest: "/tmp/cometbft_{{ cometbft_version }}_linux_amd64.tar.gz"

        - name: Extract CometBFT
          ansible.builtin.unarchive:
            src: "/tmp/cometbft_{{ cometbft_version }}_linux_amd64.tar.gz"
            dest: "/root/xian-core/"
            remote_src: yes
            creates: "/root/xian-core/cometbft"

        - name: Initialize CometBFT
          ansible.builtin.command:
            cmd: "./cometbft init"
            chdir: "/root/xian-core/"

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install PM2 globally using npm
      ansible.builtin.command:
        cmd: npm install pm2@latest -g

    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Allow CometBFT REST API port
      ufw:
        rule: allow
        port: 26657
        proto: tcp

    - name: Allow CometBFT Node Communication port
      ufw:
        rule: allow
        port: 26656
        proto: tcp

    - name: Allow CometBFT Prometheus Metrics port
      ufw:
        rule: allow
        port: 26660
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        policy: allow
        direction: incoming

  handlers:
    - name: Add deadsnakes PPA
      apt_repository:
        repo: "ppa:deadsnakes/ppa"
        state: present
        update_cache: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes
